name: iamfabriceg-discord-bot

services:
  discord-bot:
    image: node:18-alpine
    container_name: iamfabriceg-discord-bot
    # build: .
    # environment:
    #   - DISCORD_BOT_TOKEN=YOUR_DISCORD_BOT_TOKEN_HERE
    env_file:
      - .env
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: node src/index.js
    # ports:
    #   - "3000:3000"
    # depends_on:
    #   - mongo
    restart: always

  # mongo:
  #   image: mongo:latest
  #   volumes:
  #     - ./mongo-data:/data/db
